{% set name = "rs1090" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rs1090-{{ version }}.tar.gz
  sha256: 41b382e9de3a42860c588acc4a3fd40bc10e05b1a69244f349b0b02db1fc87cd

build:
  skip: true  # [py<39 or python_impl == 'pypy']
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.4,<2.0
    - pip
  run:
    - python
    - pandas >=2.2.0
    - typing_extensions >=4.10.0

test:
  imports:
    - rs1090
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/xoolive/rs1090/
  summary: Python binding to rs1090, a library to decode Mode S and ADS-B signals
  license: MIT
  license_file:
    - license.md
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - xoolive
