{% set name = "rs1090" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rs1090-{{ version }}.tar.gz
  sha256: 8122c8a2a476d788f97583bb8902afc8a7c76ec4d82992f24910940029d7e95b

build:
  skip: true  # [py<39 or python_impl == 'pypy']
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.4,<2.0
    - pip
  run:
    - python
    - pandas >=2.2.0
    - typing_extensions >=4.10.0
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  imports:
    - rs1090
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/xoolive/rs1090/
  summary: Python binding to rs1090, a library to decode Mode S and ADS-B signals
  license: MIT
  license_file:
    - license.md
    - THIRDPARTY.yml 

extra:
  recipe-maintainers:
    - xoolive
