{% set name = "rs1090" %}
{% set version = "0.3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/rs1090-{{ version }}.tar.gz
  sha256: 68951e4a6ca548ceceeaaaa65c9a40849ba34897409349531b44ed9c376e0a78

build:
  skip: true  # [py<39 or python_impl == 'pypy']
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                               # [ build_platform != target_platform ]
    - cross-python_{{ target_platform }}   # [ build_platform != target_platform ]
    - crossenv                             # [ build_platform != target_platform ]
    - maturin >=1.4,<2.0                   # [ build_platform != target_platform ]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.4,<2.0
    - pip
  run:
    - python
    - pandas >=2.2.0
    - typing_extensions >=4.10.0

test:
  imports:
    - rs1090
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/xoolive/rs1090/
  summary: Python binding to rs1090, a library to decode Mode S and ADS-B signals
  license: MIT
  license_file:
    - license.md
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - xoolive
